# Generated by Django 6.1 on 2026-08-27 08:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('ats_resume', 'ATS Resume'), ('linkedin_optimization', 'LinkedIn Optimization'), ('naukri_profile', 'Naukri Profile'), ('portfolio', 'Portfolio'), ('career_guidance', 'Career Guidance'), ('mock_interview', 'Mock Interview')], max_length=30)),
                ('notes', models.TextField(blank=True, help_text="Candidate's notes/requirements")),
                ('status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under Review'), ('accepted', 'Accepted for Consultation'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('declined', 'Declined')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_specialist', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['staff', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='candidates.candidateprofile')),
            ],
            options={
                'db_table': 'services_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='request_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='services.servicerequest')),
            ],
            options={
                'db_table': 'services_request_attachment',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(blank=True, choices=[('new', 'New'), ('under_review', 'Under Review'), ('accepted', 'Accepted for Consultation'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('declined', 'Declined')], max_length=20)),
                ('new_status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under Review'), ('accepted', 'Accepted for Consultation'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('declined', 'Declined')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='services.servicerequest')),
            ],
            options={
                'db_table': 'services_status_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
